language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 3.7
branches:
  only:
    - master
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - python -m venv .
install:
  - bin/pip install -r requirements.txt
script:
  - bin/buildout
  - bin/test --all
